### ISSUE TITLE
ASW plumbing

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/asw#1]
PPT ([here](https://docs.google.com/presentation/d/1wX8JotMAFQVlY6Uqf10vOlgeX5rSU1qkncq3kU4gvtE/edit?usp=sharing))

- [x] **Buy fittings** to complete asw fittings
- [ ] DI to HS: complete pipes from wall to HS tank (**waiting to glue for hs pump install**)
- [x] HS to Head tank: complete pipes from HS to wall (from bottom 1/5th of tank; glue at head tank)
- [ ] HS to Head tank: HS pump (Mike order, adapt plumbing for connection) 
- [ ] HS to Head tank: final pipe connections at head tank **(mike install)**
- [x] Install DI filters
- [ ] DI to head tank: plumb in solenoid (wire solenoid) and final connections to head (**install head tank Mike**)
- [x] borrow hole saw from maintenance
- [x] Get peristaltic acid pump to Montlake
- [ ] Set up acid peristaltic pump (power; mounting; **mike look at**))
- [x] **buy HS pump**
- [x] **find 24VDC power supply for pump**
- [x] **buy enclosure for pump power supply** (home depot 8/17)
- [ ] **Work out easy method to drain the HS tank (buy tube for this; maybe separate plugin to bypass computer control) **  
- [ ] Cut-away hatch with clear plexi lid to HS tank

**Comment by dmperez89** [comment]
@pmcelhany @michaelmaher114 
Something to think about for our meeting today: Are we leaving the lid to the rain barrel/HST on (with holes drilled in it for the pipes?)? Or will it be left open?

**Comment by pmcelhany** [comment]
@dmperez89 @michaelmaher114  
A lid seems like a good idea so stuff doesn't fall in the tank and to reduce evaporation. We need to be able to take off the lid, so maybe the pipes into the tank are attached with unions

**Comment by pmcelhany** [comment]
Combined with another issue
