### ISSUE TITLE
ASW Component Testing and Comms

### ISSUE THREAD

**Issue by michaelmaher114** [NWFSC-OA-lab/asw#10]
- [x] acid pump
- [ ] salinity transmitter with comms card
- [ ] salinity probe with onboard comms
- [x] water level sensor
- [x] UDA (need to get Fri Oct 22)
- [ ] HS pump operation

**Comment by pmcelhany** [comment]
combined with another issue

**Comment by pmcelhany** [comment]
Combined with another issue
