### ISSUE TITLE
New microscopes

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/asw#15]
- [ ] Pick up new (used) microscopes from Dawn on Dec 22.
- [ ] Sign for new scopes

**Comment by pmcelhany** [comment]
Did we ever get these?

**Comment by pmcelhany** [comment]
@dmperez89 did we get these extra scopes?

**Comment by dmperez89** [comment]
@pmcelhany yes, they are on a cart in the lab, but I don't think we've needed to use them yet.

**Comment by pmcelhany** [comment]
we seem to have enough scopes
