### ISSUE TITLE
ASW Sensors and Controls

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/asw#2]
- [x] conductivity sensor with integrated communications (HS tank) **ordered and charged**
- [ ] temperature sensor (HS tank) - evaluate the conductivity temperature probe
- [x] conductivity sensor (head tank) $300 **order communication card** (kathleen purchase - stalk vendor)
- [ ] durafet and UDA - install
- [ ] temperature sensor (head tank) - evaluate the conductivity and durafet (are durafets fast enough)
- [ ] Heaters (HS and head tank)
- [ ] labjack (only if needed for temperature)
- [ ] Ethernet switch (check with Tony or **order**)
- [ ] Relays in enclosure (for 2 heaters, HS pump, DI water solenoid) have the relays (**purchased enclosure; mike home depot 8/17**)
- [ ] computer connection (pick computer and monitor)
- [ ] water level sensor install USB

**Comment by pmcelhany** [comment]
@michaelmaher114 Mike, lets review where we are with the artificial seawater system. I think we need to update this issue...

**Comment by michaelmaher114** [comment]
Sounds good.  I think I'm going to try and go out to Manchester on Wednesday probably but I am available the rest of the week.

**Comment by pmcelhany** [comment]
Combined with another issue
