### ISSUE TITLE
SOP for salinity probe

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/asw#5]
Should we write up a short OA lab SOP/guild for the salinity probe describing calibration, settings, troubleshooting, etc.?

**Comment by dmperez89** [comment]
My SOP now lives [here](https://docs.google.com/document/d/14IsDH_83C37d63tQa3EZf1kIPZ7zOBKpgjqCsFmWSig/edit): 
Ocean Acidification Drive --> 03. OA Systems, Experiment Chemistry & Equipment--> 01.  SOPs --> ThermoScientific Orion Star A322 calibration SOP

**Comment by pmcelhany** [comment]
Hi Danielle - 
Thanks for drafting this. I made a few comments. At some point, we will want someone who has not calibrated the sensor before (Kathleen?) to give the SOP a try to see if there is any missing info.

**Comment by pmcelhany** [comment]
Draft SOP is complte

**Comment by pmcelhany** [comment]
going to reopen until this is finalized

**Comment by pmcelhany** [comment]
@dmperez89 add the step of measuring the conductivity of standard before calibration. This will give us a record of how much the instrument has drifted since the last calibration. We also need to find a better place on the OA drive for the salinity calibration log...

**Comment by dmperez89** [comment]
I added the step of measuring the standard before calibration to the SOP. I also created a new tab in the calibration log for ongoing probe measurements to look at drift. I moved the log to be in the same [folder](https://drive.google.com/drive/u/0/folders/1UaG3ILah7ACxrgPCQpb9dHjGlz4Panq2) as the SOP, but I'm still not sure if this is the best place....

**Comment by pmcelhany** [comment]
@dmperez89 How about we just put it [here](https://drive.google.com/drive/folders/14SURnhKceJB9coT7WP7DxHl8MI9YlnCK?usp=share_link) in a new folder.  There are really too many subfolder (16) so we will need to add another level of hierarchy to this at some point, but a folder named salinity seems pretty transparent for now.

**Comment by dmperez89** [comment]
Done, the calibration log is now in the salinity folder within systems, experiment chemistry, and equipment. I left the SOP in the SOPs folder for now.

**Comment by pmcelhany** [comment]
completed
