### ISSUE TITLE
OA lab electrical upgrade

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/asw#6]
- [x] Meet with 2nd electrician 
- [x] Get vendor quote from Karl (Mike contact)
- [x] Figure out funding mechanism (purchase card)
- [x] prepay work
- [x] Submit RTOW for elctrician
- [x] **Put tape on wall for outlet locaations**
- [x] Confirm date with contractor (Mike)
- [x] **Confirm who will attend on 9/13**
- [x] Scheduled for September 9/13
- [x] Review completed work (Mike on 9/17)
- [x] Request maintenance to seal where elctrical enters the room

**Comment by michaelmaher114** [comment]
Mike is meeting with another electrician on Thursday morning to get another quote.

**Comment by pmcelhany** [comment]
Great!
